################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
SRC_SRCS := 
CPP_SRCS := 
C_SRCS := 
O_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
C_UPPER_DEPS := 
CXX_DEPS := 
OBJS := 
SECONDARY_SIZE := 
COMPILED_SRCS := 
CPP_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
CODE/Button \
CODE/FOC \
CODE/MT9V03X \
CODE/Motor \
CODE/attitude_algorithm \
CODE/banlance_algorithm \
CODE/gpio \
CODE/servo \
CODE \
Libraries/infineon_libraries/Infra/Platform/Tricore/Compilers \
Libraries/infineon_libraries/Service/CpuGeneric/If \
Libraries/infineon_libraries/Service/CpuGeneric/StdIf \
Libraries/infineon_libraries/Service/CpuGeneric/SysSe/Bsp \
Libraries/infineon_libraries/Service/CpuGeneric/SysSe/Comm \
Libraries/infineon_libraries/Service/CpuGeneric/SysSe/General \
Libraries/infineon_libraries/Service/CpuGeneric/SysSe/Math \
Libraries/infineon_libraries/Service/CpuGeneric/SysSe/Time \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Asclin/Asc \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Asclin/Lin \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Asclin/Spi \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Asclin/Std \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Ccu6/Icu \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Ccu6/PwmBc \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Ccu6/PwmHl \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Ccu6/Std \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Ccu6/TPwm \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Ccu6/Timer \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Ccu6/TimerWithTrigger \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Cif/Cam \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Cif/Std \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Cpu/CStart \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Cpu/Irq \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Cpu/Std \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Cpu/Trap \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Dma/Dma \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Dma/Std \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Dsadc/Dsadc \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Dsadc/Rdc \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Dsadc/Std \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Dts/Dts \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Dts/Std \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Emem/Std \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Eray/Eray \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Eray/Std \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Eth/Phy_Pef7071 \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Eth/Std \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Fce/Crc \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Fce/Std \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Fft/Fft \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Fft/Std \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Flash/Std \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Gpt12/IncrEnc \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Gpt12/Std \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Gtm/Atom/Pwm \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Gtm/Atom/PwmHl \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Gtm/Atom/Timer \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Gtm/Std \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Gtm/Tim/In \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Gtm/Tom/Pwm \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Gtm/Tom/PwmHl \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Gtm/Tom/Timer \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Gtm/Trig \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Hssl/Hssl \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Hssl/Std \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/I2c/I2c \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/I2c/Std \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Iom/Driver \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Iom/Std \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Msc/Msc \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Msc/Std \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Mtu/Std \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Multican/Can \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Multican/Std \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Port/Io \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Port/Std \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Psi5/Psi5 \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Psi5/Std \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Psi5s/Psi5s \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Psi5s/Std \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Qspi/SpiMaster \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Qspi/SpiSlave \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Qspi/Std \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Scu/Std \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Sent/Sent \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Sent/Std \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Smu/Std \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Src/Std \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Stm/Std \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Stm/Timer \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Vadc/Adc \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/Vadc/Std \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/_Impl \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/_Lib/DataHandling \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/_Lib/InternalMux \
Libraries/infineon_libraries/iLLD/TC26B/Tricore/_PinMap \
Libraries/seekfree_libraries/common \
Libraries/seekfree_libraries \
Libraries/seekfree_peripheral \
USER \

