################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../CODE/DSP/Source/FilteringFunctions/FilteringFunctions.c \
../CODE/DSP/Source/FilteringFunctions/FilteringFunctionsF16.c \
../CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
../CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
../CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.c \
../CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
../CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
../CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.c \
../CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
../CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
../CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
../CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.c \
../CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
../CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
../CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.c \
../CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
../CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
../CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.c \
../CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
../CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.c \
../CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
../CODE/DSP/Source/FilteringFunctions/arm_conv_f32.c \
../CODE/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_conv_fast_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_conv_fast_q31.c \
../CODE/DSP/Source/FilteringFunctions/arm_conv_opt_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_conv_opt_q7.c \
../CODE/DSP/Source/FilteringFunctions/arm_conv_partial_f32.c \
../CODE/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.c \
../CODE/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.c \
../CODE/DSP/Source/FilteringFunctions/arm_conv_partial_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_conv_partial_q31.c \
../CODE/DSP/Source/FilteringFunctions/arm_conv_partial_q7.c \
../CODE/DSP/Source/FilteringFunctions/arm_conv_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_conv_q31.c \
../CODE/DSP/Source/FilteringFunctions/arm_conv_q7.c \
../CODE/DSP/Source/FilteringFunctions/arm_correlate_f16.c \
../CODE/DSP/Source/FilteringFunctions/arm_correlate_f32.c \
../CODE/DSP/Source/FilteringFunctions/arm_correlate_f64.c \
../CODE/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.c \
../CODE/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.c \
../CODE/DSP/Source/FilteringFunctions/arm_correlate_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_correlate_q31.c \
../CODE/DSP/Source/FilteringFunctions/arm_correlate_q7.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_f16.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_f32.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_f64.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_fast_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_fast_q31.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_init_f16.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_init_f32.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_init_f64.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_init_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_init_q31.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_init_q7.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_q31.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_q7.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.c \
../CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.c \
../CODE/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.c \
../CODE/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.c \
../CODE/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.c \
../CODE/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.c \
../CODE/DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.c \
../CODE/DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.c \
../CODE/DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.c \
../CODE/DSP/Source/FilteringFunctions/arm_lms_f32.c \
../CODE/DSP/Source/FilteringFunctions/arm_lms_init_f32.c \
../CODE/DSP/Source/FilteringFunctions/arm_lms_init_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_lms_init_q31.c \
../CODE/DSP/Source/FilteringFunctions/arm_lms_norm_f32.c \
../CODE/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.c \
../CODE/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.c \
../CODE/DSP/Source/FilteringFunctions/arm_lms_norm_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_lms_norm_q31.c \
../CODE/DSP/Source/FilteringFunctions/arm_lms_q15.c \
../CODE/DSP/Source/FilteringFunctions/arm_lms_q31.c 

OBJS += \
./CODE/DSP/Source/FilteringFunctions/FilteringFunctions.o \
./CODE/DSP/Source/FilteringFunctions/FilteringFunctionsF16.o \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.o \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.o \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.o \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.o \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.o \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.o \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o \
./CODE/DSP/Source/FilteringFunctions/arm_conv_f32.o \
./CODE/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_conv_fast_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_conv_fast_q31.o \
./CODE/DSP/Source/FilteringFunctions/arm_conv_opt_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_conv_opt_q7.o \
./CODE/DSP/Source/FilteringFunctions/arm_conv_partial_f32.o \
./CODE/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.o \
./CODE/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.o \
./CODE/DSP/Source/FilteringFunctions/arm_conv_partial_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_conv_partial_q31.o \
./CODE/DSP/Source/FilteringFunctions/arm_conv_partial_q7.o \
./CODE/DSP/Source/FilteringFunctions/arm_conv_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_conv_q31.o \
./CODE/DSP/Source/FilteringFunctions/arm_conv_q7.o \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_f16.o \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_f32.o \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_f64.o \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.o \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.o \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_q31.o \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_q7.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_f16.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_f32.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_f64.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_fast_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_fast_q31.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_init_f16.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_init_f32.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_init_f64.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_init_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_init_q31.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_init_q7.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_q31.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_q7.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.o \
./CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.o \
./CODE/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.o \
./CODE/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.o \
./CODE/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.o \
./CODE/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.o \
./CODE/DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.o \
./CODE/DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.o \
./CODE/DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.o \
./CODE/DSP/Source/FilteringFunctions/arm_lms_f32.o \
./CODE/DSP/Source/FilteringFunctions/arm_lms_init_f32.o \
./CODE/DSP/Source/FilteringFunctions/arm_lms_init_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_lms_init_q31.o \
./CODE/DSP/Source/FilteringFunctions/arm_lms_norm_f32.o \
./CODE/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.o \
./CODE/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.o \
./CODE/DSP/Source/FilteringFunctions/arm_lms_norm_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_lms_norm_q31.o \
./CODE/DSP/Source/FilteringFunctions/arm_lms_q15.o \
./CODE/DSP/Source/FilteringFunctions/arm_lms_q31.o 

COMPILED_SRCS += \
./CODE/DSP/Source/FilteringFunctions/FilteringFunctions.src \
./CODE/DSP/Source/FilteringFunctions/FilteringFunctionsF16.src \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.src \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.src \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.src \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.src \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.src \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.src \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.src \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.src \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.src \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.src \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.src \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.src \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.src \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.src \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.src \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.src \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.src \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.src \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.src \
./CODE/DSP/Source/FilteringFunctions/arm_conv_f32.src \
./CODE/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_conv_fast_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_conv_fast_q31.src \
./CODE/DSP/Source/FilteringFunctions/arm_conv_opt_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_conv_opt_q7.src \
./CODE/DSP/Source/FilteringFunctions/arm_conv_partial_f32.src \
./CODE/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.src \
./CODE/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.src \
./CODE/DSP/Source/FilteringFunctions/arm_conv_partial_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_conv_partial_q31.src \
./CODE/DSP/Source/FilteringFunctions/arm_conv_partial_q7.src \
./CODE/DSP/Source/FilteringFunctions/arm_conv_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_conv_q31.src \
./CODE/DSP/Source/FilteringFunctions/arm_conv_q7.src \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_f16.src \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_f32.src \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_f64.src \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.src \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.src \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_q31.src \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_q7.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_f16.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_f32.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_f64.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_fast_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_fast_q31.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_init_f16.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_init_f32.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_init_f64.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_init_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_init_q31.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_init_q7.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_q31.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_q7.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.src \
./CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.src \
./CODE/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.src \
./CODE/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.src \
./CODE/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.src \
./CODE/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.src \
./CODE/DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.src \
./CODE/DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.src \
./CODE/DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.src \
./CODE/DSP/Source/FilteringFunctions/arm_lms_f32.src \
./CODE/DSP/Source/FilteringFunctions/arm_lms_init_f32.src \
./CODE/DSP/Source/FilteringFunctions/arm_lms_init_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_lms_init_q31.src \
./CODE/DSP/Source/FilteringFunctions/arm_lms_norm_f32.src \
./CODE/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.src \
./CODE/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.src \
./CODE/DSP/Source/FilteringFunctions/arm_lms_norm_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_lms_norm_q31.src \
./CODE/DSP/Source/FilteringFunctions/arm_lms_q15.src \
./CODE/DSP/Source/FilteringFunctions/arm_lms_q31.src 

C_DEPS += \
./CODE/DSP/Source/FilteringFunctions/FilteringFunctions.d \
./CODE/DSP/Source/FilteringFunctions/FilteringFunctionsF16.d \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.d \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.d \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.d \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.d \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.d \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.d \
./CODE/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d \
./CODE/DSP/Source/FilteringFunctions/arm_conv_f32.d \
./CODE/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_conv_fast_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_conv_fast_q31.d \
./CODE/DSP/Source/FilteringFunctions/arm_conv_opt_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_conv_opt_q7.d \
./CODE/DSP/Source/FilteringFunctions/arm_conv_partial_f32.d \
./CODE/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.d \
./CODE/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.d \
./CODE/DSP/Source/FilteringFunctions/arm_conv_partial_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_conv_partial_q31.d \
./CODE/DSP/Source/FilteringFunctions/arm_conv_partial_q7.d \
./CODE/DSP/Source/FilteringFunctions/arm_conv_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_conv_q31.d \
./CODE/DSP/Source/FilteringFunctions/arm_conv_q7.d \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_f16.d \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_f32.d \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_f64.d \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.d \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.d \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_q31.d \
./CODE/DSP/Source/FilteringFunctions/arm_correlate_q7.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_f16.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_f32.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_f64.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_fast_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_fast_q31.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_init_f16.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_init_f32.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_init_f64.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_init_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_init_q31.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_init_q7.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_q31.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_q7.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.d \
./CODE/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.d \
./CODE/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.d \
./CODE/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.d \
./CODE/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.d \
./CODE/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.d \
./CODE/DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.d \
./CODE/DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.d \
./CODE/DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.d \
./CODE/DSP/Source/FilteringFunctions/arm_lms_f32.d \
./CODE/DSP/Source/FilteringFunctions/arm_lms_init_f32.d \
./CODE/DSP/Source/FilteringFunctions/arm_lms_init_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_lms_init_q31.d \
./CODE/DSP/Source/FilteringFunctions/arm_lms_norm_f32.d \
./CODE/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.d \
./CODE/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.d \
./CODE/DSP/Source/FilteringFunctions/arm_lms_norm_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_lms_norm_q31.d \
./CODE/DSP/Source/FilteringFunctions/arm_lms_q15.d \
./CODE/DSP/Source/FilteringFunctions/arm_lms_q31.d 


# Each subdirectory must supply rules for building sources it contributes
CODE/DSP/Source/FilteringFunctions/%.src: ../CODE/DSP/Source/FilteringFunctions/%.c CODE/DSP/Source/FilteringFunctions/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: TASKING C/C++ Compiler'
	cctc -D__CPU__=tc26xb "-fD:/FreeScale/ADS/work_space/Bald_Falcon_75/Debug/TASKING_C_C___Compiler-Include_paths.opt" --iso=99 --c++14 --language=+volatile --exceptions --anachronisms --fp-model=3 -O0 --tradeoff=4 --compact-max-size=200 -g -Wc-w544 -Wc-w557 -Ctc26xb -o "$@"  "$<"  -cs --dep-file="$(@:.src=.d)" --misrac-version=2012 -N0 -Z0 -Y0 2>&1;
	@echo 'Finished building: $<'
	@echo ' '

CODE/DSP/Source/FilteringFunctions/%.o: ./CODE/DSP/Source/FilteringFunctions/%.src CODE/DSP/Source/FilteringFunctions/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: TASKING Assembler'
	astc -Og -Os --no-warnings= --error-limit=42 -o  "$@" "$<" --list-format=L1 --optimize=gs
	@echo 'Finished building: $<'
	@echo ' '


