################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../CODE/DSP/Source/StatisticsFunctions/StatisticsFunctions.c \
../CODE/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.c \
../CODE/DSP/Source/StatisticsFunctions/arm_absmax_f16.c \
../CODE/DSP/Source/StatisticsFunctions/arm_absmax_f32.c \
../CODE/DSP/Source/StatisticsFunctions/arm_absmax_f64.c \
../CODE/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.c \
../CODE/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.c \
../CODE/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.c \
../CODE/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.c \
../CODE/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.c \
../CODE/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.c \
../CODE/DSP/Source/StatisticsFunctions/arm_absmax_q15.c \
../CODE/DSP/Source/StatisticsFunctions/arm_absmax_q31.c \
../CODE/DSP/Source/StatisticsFunctions/arm_absmax_q7.c \
../CODE/DSP/Source/StatisticsFunctions/arm_absmin_f16.c \
../CODE/DSP/Source/StatisticsFunctions/arm_absmin_f32.c \
../CODE/DSP/Source/StatisticsFunctions/arm_absmin_f64.c \
../CODE/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.c \
../CODE/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.c \
../CODE/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.c \
../CODE/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.c \
../CODE/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.c \
../CODE/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.c \
../CODE/DSP/Source/StatisticsFunctions/arm_absmin_q15.c \
../CODE/DSP/Source/StatisticsFunctions/arm_absmin_q31.c \
../CODE/DSP/Source/StatisticsFunctions/arm_absmin_q7.c \
../CODE/DSP/Source/StatisticsFunctions/arm_entropy_f16.c \
../CODE/DSP/Source/StatisticsFunctions/arm_entropy_f32.c \
../CODE/DSP/Source/StatisticsFunctions/arm_entropy_f64.c \
../CODE/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.c \
../CODE/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.c \
../CODE/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.c \
../CODE/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.c \
../CODE/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.c \
../CODE/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.c \
../CODE/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.c \
../CODE/DSP/Source/StatisticsFunctions/arm_max_f16.c \
../CODE/DSP/Source/StatisticsFunctions/arm_max_f32.c \
../CODE/DSP/Source/StatisticsFunctions/arm_max_f64.c \
../CODE/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.c \
../CODE/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.c \
../CODE/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.c \
../CODE/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.c \
../CODE/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.c \
../CODE/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.c \
../CODE/DSP/Source/StatisticsFunctions/arm_max_q15.c \
../CODE/DSP/Source/StatisticsFunctions/arm_max_q31.c \
../CODE/DSP/Source/StatisticsFunctions/arm_max_q7.c \
../CODE/DSP/Source/StatisticsFunctions/arm_mean_f16.c \
../CODE/DSP/Source/StatisticsFunctions/arm_mean_f32.c \
../CODE/DSP/Source/StatisticsFunctions/arm_mean_f64.c \
../CODE/DSP/Source/StatisticsFunctions/arm_mean_q15.c \
../CODE/DSP/Source/StatisticsFunctions/arm_mean_q31.c \
../CODE/DSP/Source/StatisticsFunctions/arm_mean_q7.c \
../CODE/DSP/Source/StatisticsFunctions/arm_min_f16.c \
../CODE/DSP/Source/StatisticsFunctions/arm_min_f32.c \
../CODE/DSP/Source/StatisticsFunctions/arm_min_f64.c \
../CODE/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.c \
../CODE/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.c \
../CODE/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.c \
../CODE/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.c \
../CODE/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.c \
../CODE/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.c \
../CODE/DSP/Source/StatisticsFunctions/arm_min_q15.c \
../CODE/DSP/Source/StatisticsFunctions/arm_min_q31.c \
../CODE/DSP/Source/StatisticsFunctions/arm_min_q7.c \
../CODE/DSP/Source/StatisticsFunctions/arm_mse_f16.c \
../CODE/DSP/Source/StatisticsFunctions/arm_mse_f32.c \
../CODE/DSP/Source/StatisticsFunctions/arm_mse_f64.c \
../CODE/DSP/Source/StatisticsFunctions/arm_mse_q15.c \
../CODE/DSP/Source/StatisticsFunctions/arm_mse_q31.c \
../CODE/DSP/Source/StatisticsFunctions/arm_mse_q7.c \
../CODE/DSP/Source/StatisticsFunctions/arm_power_f16.c \
../CODE/DSP/Source/StatisticsFunctions/arm_power_f32.c \
../CODE/DSP/Source/StatisticsFunctions/arm_power_f64.c \
../CODE/DSP/Source/StatisticsFunctions/arm_power_q15.c \
../CODE/DSP/Source/StatisticsFunctions/arm_power_q31.c \
../CODE/DSP/Source/StatisticsFunctions/arm_power_q7.c \
../CODE/DSP/Source/StatisticsFunctions/arm_rms_f16.c \
../CODE/DSP/Source/StatisticsFunctions/arm_rms_f32.c \
../CODE/DSP/Source/StatisticsFunctions/arm_rms_q15.c \
../CODE/DSP/Source/StatisticsFunctions/arm_rms_q31.c \
../CODE/DSP/Source/StatisticsFunctions/arm_std_f16.c \
../CODE/DSP/Source/StatisticsFunctions/arm_std_f32.c \
../CODE/DSP/Source/StatisticsFunctions/arm_std_f64.c \
../CODE/DSP/Source/StatisticsFunctions/arm_std_q15.c \
../CODE/DSP/Source/StatisticsFunctions/arm_std_q31.c \
../CODE/DSP/Source/StatisticsFunctions/arm_var_f16.c \
../CODE/DSP/Source/StatisticsFunctions/arm_var_f32.c \
../CODE/DSP/Source/StatisticsFunctions/arm_var_f64.c \
../CODE/DSP/Source/StatisticsFunctions/arm_var_q15.c \
../CODE/DSP/Source/StatisticsFunctions/arm_var_q31.c 

OBJS += \
./CODE/DSP/Source/StatisticsFunctions/StatisticsFunctions.o \
./CODE/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.o \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_f16.o \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_f32.o \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_f64.o \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_q15.o \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_q31.o \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_q7.o \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_f16.o \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_f32.o \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_f64.o \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_q15.o \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_q31.o \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_q7.o \
./CODE/DSP/Source/StatisticsFunctions/arm_entropy_f16.o \
./CODE/DSP/Source/StatisticsFunctions/arm_entropy_f32.o \
./CODE/DSP/Source/StatisticsFunctions/arm_entropy_f64.o \
./CODE/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.o \
./CODE/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.o \
./CODE/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.o \
./CODE/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o \
./CODE/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o \
./CODE/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.o \
./CODE/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.o \
./CODE/DSP/Source/StatisticsFunctions/arm_max_f16.o \
./CODE/DSP/Source/StatisticsFunctions/arm_max_f32.o \
./CODE/DSP/Source/StatisticsFunctions/arm_max_f64.o \
./CODE/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.o \
./CODE/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.o \
./CODE/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.o \
./CODE/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.o \
./CODE/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.o \
./CODE/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.o \
./CODE/DSP/Source/StatisticsFunctions/arm_max_q15.o \
./CODE/DSP/Source/StatisticsFunctions/arm_max_q31.o \
./CODE/DSP/Source/StatisticsFunctions/arm_max_q7.o \
./CODE/DSP/Source/StatisticsFunctions/arm_mean_f16.o \
./CODE/DSP/Source/StatisticsFunctions/arm_mean_f32.o \
./CODE/DSP/Source/StatisticsFunctions/arm_mean_f64.o \
./CODE/DSP/Source/StatisticsFunctions/arm_mean_q15.o \
./CODE/DSP/Source/StatisticsFunctions/arm_mean_q31.o \
./CODE/DSP/Source/StatisticsFunctions/arm_mean_q7.o \
./CODE/DSP/Source/StatisticsFunctions/arm_min_f16.o \
./CODE/DSP/Source/StatisticsFunctions/arm_min_f32.o \
./CODE/DSP/Source/StatisticsFunctions/arm_min_f64.o \
./CODE/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.o \
./CODE/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.o \
./CODE/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.o \
./CODE/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.o \
./CODE/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.o \
./CODE/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.o \
./CODE/DSP/Source/StatisticsFunctions/arm_min_q15.o \
./CODE/DSP/Source/StatisticsFunctions/arm_min_q31.o \
./CODE/DSP/Source/StatisticsFunctions/arm_min_q7.o \
./CODE/DSP/Source/StatisticsFunctions/arm_mse_f16.o \
./CODE/DSP/Source/StatisticsFunctions/arm_mse_f32.o \
./CODE/DSP/Source/StatisticsFunctions/arm_mse_f64.o \
./CODE/DSP/Source/StatisticsFunctions/arm_mse_q15.o \
./CODE/DSP/Source/StatisticsFunctions/arm_mse_q31.o \
./CODE/DSP/Source/StatisticsFunctions/arm_mse_q7.o \
./CODE/DSP/Source/StatisticsFunctions/arm_power_f16.o \
./CODE/DSP/Source/StatisticsFunctions/arm_power_f32.o \
./CODE/DSP/Source/StatisticsFunctions/arm_power_f64.o \
./CODE/DSP/Source/StatisticsFunctions/arm_power_q15.o \
./CODE/DSP/Source/StatisticsFunctions/arm_power_q31.o \
./CODE/DSP/Source/StatisticsFunctions/arm_power_q7.o \
./CODE/DSP/Source/StatisticsFunctions/arm_rms_f16.o \
./CODE/DSP/Source/StatisticsFunctions/arm_rms_f32.o \
./CODE/DSP/Source/StatisticsFunctions/arm_rms_q15.o \
./CODE/DSP/Source/StatisticsFunctions/arm_rms_q31.o \
./CODE/DSP/Source/StatisticsFunctions/arm_std_f16.o \
./CODE/DSP/Source/StatisticsFunctions/arm_std_f32.o \
./CODE/DSP/Source/StatisticsFunctions/arm_std_f64.o \
./CODE/DSP/Source/StatisticsFunctions/arm_std_q15.o \
./CODE/DSP/Source/StatisticsFunctions/arm_std_q31.o \
./CODE/DSP/Source/StatisticsFunctions/arm_var_f16.o \
./CODE/DSP/Source/StatisticsFunctions/arm_var_f32.o \
./CODE/DSP/Source/StatisticsFunctions/arm_var_f64.o \
./CODE/DSP/Source/StatisticsFunctions/arm_var_q15.o \
./CODE/DSP/Source/StatisticsFunctions/arm_var_q31.o 

COMPILED_SRCS += \
./CODE/DSP/Source/StatisticsFunctions/StatisticsFunctions.src \
./CODE/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.src \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_f16.src \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_f32.src \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_f64.src \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.src \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.src \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.src \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.src \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.src \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.src \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_q15.src \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_q31.src \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_q7.src \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_f16.src \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_f32.src \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_f64.src \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.src \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.src \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.src \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.src \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.src \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.src \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_q15.src \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_q31.src \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_q7.src \
./CODE/DSP/Source/StatisticsFunctions/arm_entropy_f16.src \
./CODE/DSP/Source/StatisticsFunctions/arm_entropy_f32.src \
./CODE/DSP/Source/StatisticsFunctions/arm_entropy_f64.src \
./CODE/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.src \
./CODE/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.src \
./CODE/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.src \
./CODE/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.src \
./CODE/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.src \
./CODE/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.src \
./CODE/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.src \
./CODE/DSP/Source/StatisticsFunctions/arm_max_f16.src \
./CODE/DSP/Source/StatisticsFunctions/arm_max_f32.src \
./CODE/DSP/Source/StatisticsFunctions/arm_max_f64.src \
./CODE/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.src \
./CODE/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.src \
./CODE/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.src \
./CODE/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.src \
./CODE/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.src \
./CODE/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.src \
./CODE/DSP/Source/StatisticsFunctions/arm_max_q15.src \
./CODE/DSP/Source/StatisticsFunctions/arm_max_q31.src \
./CODE/DSP/Source/StatisticsFunctions/arm_max_q7.src \
./CODE/DSP/Source/StatisticsFunctions/arm_mean_f16.src \
./CODE/DSP/Source/StatisticsFunctions/arm_mean_f32.src \
./CODE/DSP/Source/StatisticsFunctions/arm_mean_f64.src \
./CODE/DSP/Source/StatisticsFunctions/arm_mean_q15.src \
./CODE/DSP/Source/StatisticsFunctions/arm_mean_q31.src \
./CODE/DSP/Source/StatisticsFunctions/arm_mean_q7.src \
./CODE/DSP/Source/StatisticsFunctions/arm_min_f16.src \
./CODE/DSP/Source/StatisticsFunctions/arm_min_f32.src \
./CODE/DSP/Source/StatisticsFunctions/arm_min_f64.src \
./CODE/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.src \
./CODE/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.src \
./CODE/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.src \
./CODE/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.src \
./CODE/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.src \
./CODE/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.src \
./CODE/DSP/Source/StatisticsFunctions/arm_min_q15.src \
./CODE/DSP/Source/StatisticsFunctions/arm_min_q31.src \
./CODE/DSP/Source/StatisticsFunctions/arm_min_q7.src \
./CODE/DSP/Source/StatisticsFunctions/arm_mse_f16.src \
./CODE/DSP/Source/StatisticsFunctions/arm_mse_f32.src \
./CODE/DSP/Source/StatisticsFunctions/arm_mse_f64.src \
./CODE/DSP/Source/StatisticsFunctions/arm_mse_q15.src \
./CODE/DSP/Source/StatisticsFunctions/arm_mse_q31.src \
./CODE/DSP/Source/StatisticsFunctions/arm_mse_q7.src \
./CODE/DSP/Source/StatisticsFunctions/arm_power_f16.src \
./CODE/DSP/Source/StatisticsFunctions/arm_power_f32.src \
./CODE/DSP/Source/StatisticsFunctions/arm_power_f64.src \
./CODE/DSP/Source/StatisticsFunctions/arm_power_q15.src \
./CODE/DSP/Source/StatisticsFunctions/arm_power_q31.src \
./CODE/DSP/Source/StatisticsFunctions/arm_power_q7.src \
./CODE/DSP/Source/StatisticsFunctions/arm_rms_f16.src \
./CODE/DSP/Source/StatisticsFunctions/arm_rms_f32.src \
./CODE/DSP/Source/StatisticsFunctions/arm_rms_q15.src \
./CODE/DSP/Source/StatisticsFunctions/arm_rms_q31.src \
./CODE/DSP/Source/StatisticsFunctions/arm_std_f16.src \
./CODE/DSP/Source/StatisticsFunctions/arm_std_f32.src \
./CODE/DSP/Source/StatisticsFunctions/arm_std_f64.src \
./CODE/DSP/Source/StatisticsFunctions/arm_std_q15.src \
./CODE/DSP/Source/StatisticsFunctions/arm_std_q31.src \
./CODE/DSP/Source/StatisticsFunctions/arm_var_f16.src \
./CODE/DSP/Source/StatisticsFunctions/arm_var_f32.src \
./CODE/DSP/Source/StatisticsFunctions/arm_var_f64.src \
./CODE/DSP/Source/StatisticsFunctions/arm_var_q15.src \
./CODE/DSP/Source/StatisticsFunctions/arm_var_q31.src 

C_DEPS += \
./CODE/DSP/Source/StatisticsFunctions/StatisticsFunctions.d \
./CODE/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.d \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_f16.d \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_f32.d \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_f64.d \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_q15.d \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_q31.d \
./CODE/DSP/Source/StatisticsFunctions/arm_absmax_q7.d \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_f16.d \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_f32.d \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_f64.d \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_q15.d \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_q31.d \
./CODE/DSP/Source/StatisticsFunctions/arm_absmin_q7.d \
./CODE/DSP/Source/StatisticsFunctions/arm_entropy_f16.d \
./CODE/DSP/Source/StatisticsFunctions/arm_entropy_f32.d \
./CODE/DSP/Source/StatisticsFunctions/arm_entropy_f64.d \
./CODE/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.d \
./CODE/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.d \
./CODE/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.d \
./CODE/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d \
./CODE/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d \
./CODE/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.d \
./CODE/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.d \
./CODE/DSP/Source/StatisticsFunctions/arm_max_f16.d \
./CODE/DSP/Source/StatisticsFunctions/arm_max_f32.d \
./CODE/DSP/Source/StatisticsFunctions/arm_max_f64.d \
./CODE/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.d \
./CODE/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.d \
./CODE/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.d \
./CODE/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.d \
./CODE/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.d \
./CODE/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.d \
./CODE/DSP/Source/StatisticsFunctions/arm_max_q15.d \
./CODE/DSP/Source/StatisticsFunctions/arm_max_q31.d \
./CODE/DSP/Source/StatisticsFunctions/arm_max_q7.d \
./CODE/DSP/Source/StatisticsFunctions/arm_mean_f16.d \
./CODE/DSP/Source/StatisticsFunctions/arm_mean_f32.d \
./CODE/DSP/Source/StatisticsFunctions/arm_mean_f64.d \
./CODE/DSP/Source/StatisticsFunctions/arm_mean_q15.d \
./CODE/DSP/Source/StatisticsFunctions/arm_mean_q31.d \
./CODE/DSP/Source/StatisticsFunctions/arm_mean_q7.d \
./CODE/DSP/Source/StatisticsFunctions/arm_min_f16.d \
./CODE/DSP/Source/StatisticsFunctions/arm_min_f32.d \
./CODE/DSP/Source/StatisticsFunctions/arm_min_f64.d \
./CODE/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.d \
./CODE/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.d \
./CODE/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.d \
./CODE/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.d \
./CODE/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.d \
./CODE/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.d \
./CODE/DSP/Source/StatisticsFunctions/arm_min_q15.d \
./CODE/DSP/Source/StatisticsFunctions/arm_min_q31.d \
./CODE/DSP/Source/StatisticsFunctions/arm_min_q7.d \
./CODE/DSP/Source/StatisticsFunctions/arm_mse_f16.d \
./CODE/DSP/Source/StatisticsFunctions/arm_mse_f32.d \
./CODE/DSP/Source/StatisticsFunctions/arm_mse_f64.d \
./CODE/DSP/Source/StatisticsFunctions/arm_mse_q15.d \
./CODE/DSP/Source/StatisticsFunctions/arm_mse_q31.d \
./CODE/DSP/Source/StatisticsFunctions/arm_mse_q7.d \
./CODE/DSP/Source/StatisticsFunctions/arm_power_f16.d \
./CODE/DSP/Source/StatisticsFunctions/arm_power_f32.d \
./CODE/DSP/Source/StatisticsFunctions/arm_power_f64.d \
./CODE/DSP/Source/StatisticsFunctions/arm_power_q15.d \
./CODE/DSP/Source/StatisticsFunctions/arm_power_q31.d \
./CODE/DSP/Source/StatisticsFunctions/arm_power_q7.d \
./CODE/DSP/Source/StatisticsFunctions/arm_rms_f16.d \
./CODE/DSP/Source/StatisticsFunctions/arm_rms_f32.d \
./CODE/DSP/Source/StatisticsFunctions/arm_rms_q15.d \
./CODE/DSP/Source/StatisticsFunctions/arm_rms_q31.d \
./CODE/DSP/Source/StatisticsFunctions/arm_std_f16.d \
./CODE/DSP/Source/StatisticsFunctions/arm_std_f32.d \
./CODE/DSP/Source/StatisticsFunctions/arm_std_f64.d \
./CODE/DSP/Source/StatisticsFunctions/arm_std_q15.d \
./CODE/DSP/Source/StatisticsFunctions/arm_std_q31.d \
./CODE/DSP/Source/StatisticsFunctions/arm_var_f16.d \
./CODE/DSP/Source/StatisticsFunctions/arm_var_f32.d \
./CODE/DSP/Source/StatisticsFunctions/arm_var_f64.d \
./CODE/DSP/Source/StatisticsFunctions/arm_var_q15.d \
./CODE/DSP/Source/StatisticsFunctions/arm_var_q31.d 


# Each subdirectory must supply rules for building sources it contributes
CODE/DSP/Source/StatisticsFunctions/%.src: ../CODE/DSP/Source/StatisticsFunctions/%.c CODE/DSP/Source/StatisticsFunctions/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: TASKING C/C++ Compiler'
	cctc -D__CPU__=tc26xb "-fD:/FreeScale/ADS/work_space/Bald_Falcon_75/Debug/TASKING_C_C___Compiler-Include_paths.opt" --iso=99 --c++14 --language=+volatile --exceptions --anachronisms --fp-model=3 -O0 --tradeoff=4 --compact-max-size=200 -g -Wc-w544 -Wc-w557 -Ctc26xb -o "$@"  "$<"  -cs --dep-file="$(@:.src=.d)" --misrac-version=2012 -N0 -Z0 -Y0 2>&1;
	@echo 'Finished building: $<'
	@echo ' '

CODE/DSP/Source/StatisticsFunctions/%.o: ./CODE/DSP/Source/StatisticsFunctions/%.src CODE/DSP/Source/StatisticsFunctions/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: TASKING Assembler'
	astc -Og -Os --no-warnings= --error-limit=42 -o  "$@" "$<" --list-format=L1 --optimize=gs
	@echo 'Finished building: $<'
	@echo ' '


